import { Task } from "../../../node_modules/gantt-task-react/dist/types/public-types";

export function initTasks() {
  const currentDate = new Date();
  const tasks: Task[] = [
    // {
    //   start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 1),
    //   end: new Date(currentDate.getFullYear(), currentDate.getMonth(), 15),
    //   name: "",
    //   gosiwon: "영등포 고시원",
    //   roomName: "영등포 고시원",
    //   id: "ProjectSample",
    //   progress: 100,
    //   type: "project",
    //   hideChildren: false,
    //   displayOrder: 1,
    // },
    {
      start: new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1),
      end: new Date(
        currentDate.getFullYear(),
        currentDate.getMonth(),
        2,
        12,
        28
      ),
      name: "",
      id: "Task 0",
      progress: 100,
      type: "task",
      // project: "ProjectSample",
      displayOrder: 2,
      gosiwon: "영등포 고시원",
      roomName: "101호(블레스룸)",
      roomStatus: "이용중",
      roomInfo: "101호 블레스룸 / 원룸형 / 외창",
      contractName: "김한수",
      depositName: "김한수",
      enterName: "김한수",
      contractInfo: "김한수 / 34 / M(010-1234-5678)",
      contractStatus: "퇴실 확정",
      roomSize: "원룸",
      roomType: "외창",
      contractAmount: "200000",
      styles: {
        progressColor: "#D86F6F",
        backgroundColor: "#D86F6F",
        backgroundSelectedColor: "#D86F6F33",
        barProgressSelectedBorderColor: "#A93434",
        // progressSelectedColor:
      },
    },
    {
      start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 2),
      end: new Date(
        currentDate.getFullYear(),
        currentDate.getMonth() + 1,
        4,
        0,
        0
      ),
      name: "",
      id: "Task 1",
      progress: 100,
      // dependencies: ["Task 0"],
      type: "task",
      // project: "ProjectSample",
      displayOrder: 3,
      gosiwon: "영등포 고시원",
      roomName: "102호(블레스룸)",
      roomStatus: "판매중",
      roomInfo: "102호 블레스룸 / 원룸형 / 외창",
      contractName: "홍길동",
      depositName: "홍길동",
      enterName: "홍길동",
      contractStatus: "퇴실 확정",
      roomSize: "원룸",
      roomType: "외창",
      contractAmount: "200000",
      styles: {
        progressColor: "#5D6EE2",
        backgroundColor: "#5D6EE2",
        backgroundSelectedColor: "#5D6EE233",
        barProgressSelectedBorderColor: "#495057",
      },
    },
    {
      start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 4),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), 8, 0, 0),
      name: "",
      id: "Task 2",
      progress: 100,
      // dependencies: ["Task 1"],
      type: "task",
      // project: "ProjectSample",
      displayOrder: 4,
      gosiwon: "영등포 고시원",
      roomName: "103호(그레이스룸)",
      roomStatus: "판매중",
      roomInfo: "103호 그레이스룸 / 원룸형 / 외창",
      contractName: "이현수",
      depositName: "이현수",
      enterName: "이현수",
      contractStatus: "퇴실 확정",
      roomSize: "원룸",
      roomType: "외창",
      contractAmount: "200000",
      styles: {
        progressColor: "#5D6EE2",
        backgroundColor: "#5D6EE2",
        backgroundSelectedColor: "#5D6EE233",
        barProgressSelectedBorderColor: "#495057",
      },
    },
    {
      start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 8),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), 9, 0, 0),
      name: "",
      id: "Task 3",
      progress: 100,
      // dependencies: ["Task 2"],
      type: "task",
      // project: "ProjectSample",
      displayOrder: 5,
      gosiwon: "영등포 고시원",
      roomName: "104호(블레스룸)",
      roomStatus: "판매중",
      roomInfo: "104호 블레스룸 / 원룸형 / 외창",
      contractName: "김철수",
      depositName: "김철수",
      enterName: "김철수",
      contractStatus: "퇴실 확정",
      roomSize: "원룸",
      roomType: "외창",
      contractAmount: "200000",
      styles: {
        progressColor: "#5D6EE2",
        backgroundColor: "#5D6EE2",
        backgroundSelectedColor: "#5D6EE233",
        barProgressSelectedBorderColor: "#495057",
      },
    },
    {
      start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 8),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), 10),
      name: "",
      id: "Task 4",
      type: "task",
      progress: 100,
      // dependencies: ["Task 2"],
      // project: "ProjectSample",
      displayOrder: 6,
      gosiwon: "영등포 고시원",
      roomName: "105호(블레스룸)",
      roomStatus: "판매중",
      roomInfo: "105호 블레스룸 / 원룸형 / 외창",
      contractName: "최영희",
      depositName: "최영희",
      enterName: "최영희",
      contractStatus: "퇴실 확정",
      roomSize: "원룸",
      roomType: "외창",
      contractAmount: "200000",
      styles: {
        progressColor: "#5D6EE2",
        backgroundColor: "#5D6EE2",
        backgroundSelectedColor: "#5D6EE233",
        barProgressSelectedBorderColor: "#495057",
      },
    },
    {
      start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 8),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), 10),
      name: "",
      id: "Task 5",
      type: "task",
      progress: 100,
      // dependencies: ["Task 2"],
      // project: "ProjectSample",
      displayOrder: 7,
      gosiwon: "영등포 고시원",
      roomName: "105호(블레스룸)",
      roomStatus: "판매중",
      roomInfo: "105호 블레스룸 / 원룸형 / 외창",
      contractName: "최영희",
      depositName: "최영희",
      enterName: "최영희",
      contractStatus: "퇴실 확정",
      roomSize: "원룸",
      roomType: "외창",
      contractAmount: "200000",
      styles: {
        progressColor: "#5D6EE2",
        backgroundColor: "#5D6EE2",
        backgroundSelectedColor: "#5D6EE233",
        barProgressSelectedBorderColor: "#495057",
      },
    },
    {
      start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 8),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), 10),
      name: "",
      id: "Task 6",
      type: "task",
      progress: 100,
      // dependencies: ["Task 2"],
      // project: "ProjectSample",
      displayOrder: 8,
      gosiwon: "영등포 고시원",
      roomName: "105호(블레스룸)",
      roomStatus: "판매중",
      roomInfo: "105호 블레스룸 / 원룸형 / 외창",
      contractName: "최영희",
      depositName: "최영희",
      enterName: "최영희",
      contractStatus: "퇴실 확정",
      roomSize: "원룸",
      roomType: "외창",
      contractAmount: "200000",
      styles: {
        progressColor: "#5D6EE2",
        backgroundColor: "#5D6EE2",
        backgroundSelectedColor: "#5D6EE233",
        barProgressSelectedBorderColor: "#495057",
      },
    },
    {
      start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 8),
      end: new Date(currentDate.getFullYear(), currentDate.getMonth(), 10),
      name: "",
      id: "Task 7",
      type: "task",
      progress: 100,
      // dependencies: ["Task 2"],
      // project: "ProjectSample",
      displayOrder: 9,
      gosiwon: "영등포 고시원",
      roomName: "105호(블레스룸)",
      roomStatus: "판매중",
      roomInfo: "105호 블레스룸 / 원룸형 / 외창",
      contractName: "최영희",
      depositName: "최영희",
      enterName: "최영희",
      contractStatus: "퇴실 확정",
      roomSize: "원룸",
      roomType: "외창",
      contractAmount: "200000",
      styles: {
        progressColor: "#5D6EE2",
        backgroundColor: "#5D6EE2",
        backgroundSelectedColor: "#5D6EE233",
        barProgressSelectedBorderColor: "#495057",
      },
    },
    // {
    //   start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 15),
    //   end: new Date(currentDate.getFullYear(), currentDate.getMonth(), 15),
    //   name: "Release",
    //   id: "Task 6",
    //   progress: currentDate.getMonth(),
    //   type: "milestone",
    //   dependencies: ["Task 4"],
    //   project: "ProjectSample",
    //   displayOrder: 7,
    // },
    // {
    //   start: new Date(currentDate.getFullYear(), currentDate.getMonth(), 18),
    //   end: new Date(currentDate.getFullYear(), currentDate.getMonth(), 19),
    //   name: "Party Time",
    //   id: "Task 9",
    //   progress: 0,
    //   isDisabled: true,
    //   type: "task",
    // },
  ];
  return tasks;
}

export function getStartEndDateForProject(tasks: Task[], projectId: string) {
  const projectTasks = tasks.filter((t) => t.project === projectId);
  let start = projectTasks[0].start;
  let end = projectTasks[0].end;

  for (let i = 0; i < projectTasks.length; i++) {
    const task = projectTasks[i];
    if (start.getTime() > task.start.getTime()) {
      start = task.start;
    }
    if (end.getTime() < task.end.getTime()) {
      end = task.end;
    }
  }
  return [start, end];
}
