name: Build and Upload Artifact

on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages]

# GitHub Pages 배포를 위한 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 배포 방지
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build static files
        run: npm run build

      - name: Prepare dist/index.html from dashboard.ejs
        run: |
          mkdir -p dist
          cp views/pages/dashboard.ejs dist/index.html
          sed -i 's|href="/css/|href="./css/|g' dist/index.html
          sed -i 's|href="/js/|href="./js/|g' dist/index.html
          sed -i 's|src="/js/|src="./js/|g' dist/index.html
          mkdir -p dist/css dist/js
          cp -R public/css/. dist/css/ || true
          cp -R public/js/. dist/js/ || true

      - name: Include third-party licenses
        run: |
          mkdir -p dist/THIRD_PARTY_LICENSES
          cp src/gantt-task-react/LICENSE dist/THIRD_PARTY_LICENSES/gantt-task-react.LICENSE.txt || true

      - name: Assert dist/index.html exists
        run: test -f dist/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
