name: Build and Upload Artifact

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build Server and Client
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-gantt-build
          if-no-files-found: error
          path: |
            dist/**
            public/js/**
            views/**
            public/css/**
            src/gantt-task-react/LICENSE
            package.json
            package-lock.json
            vite.config.ts
            tsconfig.json
            tsconfig.node.json
