name: Build and Upload Artifact

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# GitHub Pages 배포를 위한 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 배포 방지
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build static files
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: react-gantt-build
          if-no-files-found: error
          path: |
            dist/**
            public/js/**
            views/**
            public/css/**
            src/gantt-task-react/LICENSE
            package.json
            package-lock.json
            vite.config.ts
            tsconfig.json
            tsconfig.node.json

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
